config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  resources :countries
  resources :employees do
    resources :travel_expenses
    resources :room_expenses
    resources :medical_expenses
    resources :title_ranges do
      collection do
        delete :truncate
      end
    end
    resources :spouse_ranges do
      collection do
        delete :truncate
      end
    end
    member do
      get :payroll
    end
  end
  resources :travel_expenses
  resources :room_expenses
  resources :medical_expenses
  resources :title_ranges
  resources :spouse_ranges
  get :dashboard, to: 'dashboard#index', as: :dashboard
  get :sign_in, to: 'sessions#new', as: :sign_in
  post :sign_in, to: 'sessions#create'
  get :sign_out, to: 'sessions#destroy', as: :sign_out
end

app/views/layouts/application.html.erb
<!doctype html>
<html class="fixed sidebar-dark sidebar-left-sm">
  <head>
    <meta charset="UTF-8">
    <title>Heather</title>
    <meta name="description" content="Heather">
    <meta name="author" content="Seairy">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= stylesheet_link_tag 'porto', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'modernizr', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-loading-overlay class="loading-overlay-showing">
    <span class="loading-overlay light"> 
      <span class="loader black"></span> 
    </span>
    <section class="body">
      <header class="header">
        <div class="logo-container">
          <a href="/" class="logo">
            <%= image_tag('porto/logo.png', height: 35) %>
          </a>
          <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
          </div>
        </div>
        <div class="header-right">
          <form action="pages-search-results.html" class="search nav-form">
            <div class="input-group input-search">
              <input type="text" class="form-control" name="q" id="q" placeholder="搜索...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <span class="separator"></span>
          <div id="userbox" class="userbox">
            <a href="#" data-toggle="dropdown">
              <figure class="profile-picture">
                <%= image_tag('porto/portrait-default.png') %>
              </figure>
              <div class="profile-info" data-lock-name="<%= @current_administrator.name %>">
                <span class="name"><%= @current_administrator.name %></span>
                <span class="role">管理员</span>
              </div>
              <i class="fa custom-caret"></i>
            </a>
            <div class="dropdown-menu">
              <ul class="list-unstyled">
                <li class="divider"></li>
                <li>
                  <a role="menuitem" tabindex="-1" href="pages-user-profile.html"><i class="fa fa-user"></i> 我的信息</a>
                </li>
                <li>
                  <a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-cog"></i> 修改密码</a>
                </li>
                <li>
                  <%= link_to raw('<i class="fa fa-power-off"></i> 退出登录'), sign_out_path, role: 'menuitem', tabindex: '-1' %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </header>
      <div class="inner-wrapper">
        <aside id="sidebar-left" class="sidebar-left">
          <div class="sidebar-header">
            <div class="sidebar-title">
              导航栏
            </div>
            <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
              <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
            </div>
          </div>
          <div class="nano">
            <div class="nano-content">
              <nav id="menu" class="nav-main" role="navigation">
                <ul class="nav nav-main">
                  <%= porto_nav '控制面板', 'fa fa-home', %w(dashboard), dashboard_path %>
                  <%= porto_nav '教师管理', 'fa fa-user', %w(employees) do %>
                    <li><%= link_to raw('教师列表'), employees_path %></li>
                    <li><%= link_to raw('创建教师'), new_employee_path %></li>
                  <% end %>
                </ul>
              </nav>
            </div>
            <script>
              if (typeof localStorage !== 'undefined') {
                if (localStorage.getItem('sidebar-left-position') !== null) {
                  var initialPosition = localStorage.getItem('sidebar-left-position'),
                    sidebarLeft = document.querySelector('#sidebar-left .nano-content');
                  sidebarLeft.scrollTop = initialPosition;
                }
              }
            </script>
          </div>
        </aside>
        <section role="main" class="content-body">
          <%= yield %>
        </section>
      </div>
      <aside id="sidebar-right" class="sidebar-right">
        <div class="nano">
          <div class="nano-content">
            <a href="#" class="mobile-close visible-xs">
              Collapse <i class="fa fa-chevron-right"></i>
            </a>
            <div class="sidebar-right-wrapper">
              <div class="sidebar-widget widget-calendar">
                <h6>Upcoming Tasks</h6>
                <div data-plugin-datepicker data-plugin-skin="dark" ></div>
                <ul>
                  <li>
                    <time datetime="2014-04-19T00:00+00:00">04/19/2014</time>
                    <span>Company Meeting</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </aside>
    </section>
    <%= javascript_include_tag 'porto', 'data-turbolinks-track' => true %>
    <%= content_for :javascript %>
    <script>
      jQuery(document).ready(function() {
        $('.btn-modal').magnificPopup({
          type: 'inline',
          preloader: false,
          modal: true
        });
          
        $(document).on('click', '.modal-dismiss', function (e) {
          e.preventDefault();
          $.magnificPopup.close();
        });
      });
    </script>
  </body>
</html>